# Generated by Django 2.2.8 on 2019-12-20 04:10

import Game.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_center', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation_center', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('radius', models.IntegerField()),
                ('status', django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('Finalized', 'Finalized'), ('In Progresss', 'In Progresss')], enum_class=Game.models.Status, max_length=12)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_game', to=settings.AUTH_USER_MODEL)),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clue', models.TextField()),
                ('solution', models.TextField()),
                ('address', django_google_maps.fields.AddressField(max_length=200)),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100)),
                ('treasure_img', models.ImageField(upload_to='treasure/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Treasure_Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prove_img', models.ImageField(upload_to=Game.models.user_directory_path)),
                ('prove_date', models.DateTimeField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treasure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Treasure')),
            ],
        ),
    ]
