# Generated by Django 2.2.8 on 2019-12-22 16:17

import Game.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_center', models.CharField(max_length=100)),
                ('north_east_bound', geoposition.fields.GeopositionField(max_length=42, null=True)),
                ('south_west_bound', geoposition.fields.GeopositionField(max_length=42, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Finalized'), (2, 'InProgress')], default=Game.models.Status(2))),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_game', to=settings.AUTH_USER_MODEL)),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clue', models.TextField()),
                ('solution', models.TextField()),
                ('address', models.CharField(max_length=100)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('treasure_img', models.ImageField(upload_to='treasure/%Y/%m/%d')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='Game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player_Treasure_Found',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prove_img', models.ImageField(upload_to=Game.models.user_directory_path)),
                ('prove_date', models.DateTimeField()),
                ('game_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('treasure_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Game.Treasure')),
            ],
        ),
    ]
