# Generated by Django 2.2.8 on 2020-01-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='treasure_img',
            field=models.ImageField(blank=True, null=True, upload_to='treasure/%Y/%m/%d'),
        ),
    ]
