# Generated by Django 2.2.8 on 2019-12-20 04:49

from django.db import migrations, models
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='address_center',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='game',
            name='geolocation_center',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='treasure',
            name='geolocation',
            field=geoposition.fields.GeopositionField(max_length=42),
        ),
    ]
