# Generated by Django 2.2.7 on 2019-12-14 10:25

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='geolocation',
            field=djgeojson.fields.PointField(),
        ),
    ]
