# Generated by Django 2.2.7 on 2019-12-15 17:48

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20191214_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='geolocation_center',
            field=djgeojson.fields.PointField(),
        ),
    ]
