# Generated by Django 2.2.8 on 2020-01-24 03:00

import Game.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_auto_20200123_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player_treasure_found',
            old_name='game_id',
            new_name='game',
        ),
        migrations.RenameField(
            model_name='player_treasure_found',
            old_name='treasure_id',
            new_name='treasure',
        ),
        migrations.AlterField(
            model_name='player_treasure_found',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='player_treasure_found',
            name='prove_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='player_treasure_found',
            name='prove_img',
            field=models.ImageField(blank=True, null=True, upload_to=Game.models.user_directory_path),
        ),
    ]
