# Generated by Django 2.2.8 on 2020-01-24 12:07

from django.db import migrations
import django.utils.timezone
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20200124_0400'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_treasure_found',
            name='position',
            field=geoposition.fields.GeopositionField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
    ]
