# Generated by Django 2.2.8 on 2019-12-21 14:31

from django.db import migrations
import geoposition.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_auto_20191220_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='position',
        ),
        migrations.RemoveField(
            model_name='game',
            name='radius',
        ),
        migrations.AddField(
            model_name='game',
            name='north_east_bound',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='south_west_bound',
            field=geoposition.fields.GeopositionField(max_length=42, null=True),
        ),
    ]
