# Generated by Django 2.2.8 on 2019-12-22 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_auto_20191221_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='treasure',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='Game.Game'),
            preserve_default=False,
        ),
    ]
